Daraja HTTP Framework: TdjGenericHolder Class Reference
TdjGenericHolder Class Reference
A generic holder class that manages objects of type T.
Public Member Functions
TdjGenericHolder (TInterfacedClass AClass)
Constructor for creating an instance of the class.
Boolean IsStarted ()
Boolean IsStopped ()
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
string Name
Boolean Started
Boolean Stopped
Protected Member Functions
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
DoStart ()
Execute the custom start code.
DoStop ()
Execute the custom stop code.
Detailed Description
A generic holder class that manages objects of type T.
Template Parameters
T A type parameter constrained to TInterfacedObject.
Note
This class inherits from TdjLifeCycle.
Constructor & Destructor Documentation
TdjGenericHolder()
TdjGenericHolder::TdjGenericHolder (TInterfacedClass AClass)
Constructor for creating an instance of the class.
Parameters
AClass The class type to be used for initialization.
Member Function Documentation
CheckStarted()
TdjLifeCycle::CheckStarted () protected inherited
Raises an exception if the lifecycle is in "started" state.
References Started.
Referenced by TdjHTTPConnector::DoStart(), and TdjServer::DoStart().
CheckStopped()
TdjLifeCycle::CheckStopped () protected inherited
Raises an exception if the lifecycle is in "stopped" state.
References Stopped.
Referenced by TdjServer::DoStop().
DoStart()
TdjLifeCycle::DoStart () protected inherited
Execute the custom start code.
Referenced by Start().
DoStop()
TdjLifeCycle::DoStop () protected inherited
Execute the custom stop code.
Referenced by Stop().
IsStarted()
Boolean TdjLifeCycle::IsStarted () inherited
Returns
True if component is started
Implements ILifeCycle.
Referenced by TdjHTTPConnector::~TdjHTTPConnector(), TdjHTTPConnector::DoStop(), TdjHandlerCollection::Handle(), and Start().
IsStopped()
Boolean TdjLifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implements ILifeCycle.
Start()
TdjLifeCycle::Start () inherited
Starts the component.
Implements ILifeCycle.
References DoStart(), IsStarted(), and Started.
Stop()
TdjLifeCycle::Stop () inherited
Stops the component.
Implements ILifeCycle.
References DoStop(), and Stopped.
Referenced by TdjHTTPConnector::~TdjHTTPConnector().
Member Data Documentation
Name
string TdjGenericHolder::Name
See also
FName For reading
FName For writing
Started
Boolean TdjLifeCycle::Started inherited
See also
FStarted For reading
SetStarted For writing
Referenced by TdjHandlerCollection::AddHandler(), CheckStarted(), TdjHTTPConnector::DoStart(), and Start().
Stopped
Boolean TdjLifeCycle::Stopped inherited
See also
FStopped For reading
SetStopped For writing
Referenced by CheckStopped(), and Stop().