Daraja HTTP Framework: TdjWebComponentHolder Class Reference
TdjWebComponentHolder Class Reference
Holds a WebComponent and configuration data.
Public Member Functions
TdjWebComponentHolder (TdjWebComponentClass WebComponentClass)
Constructor.
~TdjWebComponentHolder ()
Destructor.
IContext GetContext ()
Get the context.
Handle (TdjServerContext Context, TdjRequest Request, TdjResponse Response)
Boolean IsStarted ()
Boolean IsStopped ()
SetContext (const IContext Context)
Set the context.
SetInitParameter (const string Key, const string Value)
Set initialization parameter.
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
string Name
Boolean Started
Boolean Stopped
TdjWebComponent WebComponent
The instance of the Web Component.
TdjWebComponentClass WebComponentClass
The Web Component Class.
Protected Member Functions
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
DoStart ()
DoStop ()
Detailed Description
Holds a WebComponent and configuration data.
Constructor & Destructor Documentation
TdjWebComponentHolder()
TdjWebComponentHolder::TdjWebComponentHolder (TdjWebComponentClass WebComponentClass)
Constructor.
Parameters
WebComponentClass the Web Component class
References TdjWebComponentHolder(), Create(), and WebComponentClass.
Referenced by TdjWebComponentHolder().
~TdjWebComponentHolder()
TdjWebComponentHolder::~TdjWebComponentHolder ()
Destructor.
Member Function Documentation
CheckStarted()
TdjLifeCycle::CheckStarted () protected inherited
Raises an exception if the lifecycle is in "started" state.
References Started.
Referenced by TdjHTTPConnector::DoStart(), and TdjServer::DoStart().
CheckStopped()
TdjLifeCycle::CheckStopped () protected inherited
Raises an exception if the lifecycle is in "stopped" state.
References Stopped.
Referenced by TdjServer::DoStop().
DoStart()
TdjWebComponentHolder::DoStart () protected
DoStop()
TdjWebComponentHolder::DoStop () protected
GetContext()
IContext TdjWebComponentHolder::GetContext ()
Get the context.
Referenced by TdjWebComponentContextHandler::AddWebComponent().
Handle()
TdjWebComponentHolder::Handle (TdjServerContext Context, TdjRequest Request, TdjResponse Response)
References WebComponentClass.
IsStarted()
Boolean TdjLifeCycle::IsStarted () inherited
Returns
True if component is started
Implements ILifeCycle.
Referenced by TdjHTTPConnector::~TdjHTTPConnector(), TdjHTTPConnector::DoStop(), TdjHandlerCollection::Handle(), and Start().
IsStopped()
Boolean TdjLifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implements ILifeCycle.
SetContext()
TdjWebComponentHolder::SetContext (const IContext Context)
Set the context.
Parameters
Context the context
Referenced by TdjWebComponentContextHandler::AddWebComponent().
SetInitParameter()
TdjWebComponentHolder::SetInitParameter (const string Key, const string Value)
Set initialization parameter.
Parameters
Key init parameter name
Value init parameter value
Start()
TdjLifeCycle::Start () inherited
Starts the component.
Implements ILifeCycle.
References DoStart(), IsStarted(), and Started.
Stop()
TdjLifeCycle::Stop () inherited
Stops the component.
Implements ILifeCycle.
References DoStop(), and Stopped.
Referenced by TdjHTTPConnector::~TdjHTTPConnector().
Member Data Documentation
Name
string TdjGenericHolder::Name inherited
See also
FName For reading
FName For writing
Started
Boolean TdjLifeCycle::Started inherited
See also
FStarted For reading
SetStarted For writing
Referenced by TdjHandlerCollection::AddHandler(), CheckStarted(), TdjHTTPConnector::DoStart(), and Start().
Stopped
Boolean TdjLifeCycle::Stopped inherited
See also
FStopped For reading
SetStopped For writing
Referenced by CheckStopped(), and Stop().
WebComponent
TdjWebComponent TdjWebComponentHolder::WebComponent
The instance of the Web Component.
See also
GetWebComponent For reading
WebComponentClass
TdjWebComponentClass TdjWebComponentHolder::WebComponentClass
The Web Component Class.
See also
GetClass For reading
Referenced by TdjWebComponentHolder(), TdjWebComponentContextHandler::AddWebComponent(), and Handle().