Daraja HTTP Framework: TdjHTTPConnector Class Reference
TdjHTTPConnector Class Reference
HTTP connector.
Public Member Functions
TdjHTTPConnector (const IHandler Handler)
Create a HTTP connector.
~TdjHTTPConnector ()
Destructor.
Boolean IsStarted ()
Boolean IsStopped ()
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
string Host
The host address for the connector.
TdjHTTPServer HTTPServer
Integer Port
The port number for the connector.
Boolean Started
Boolean Stopped
Protected Member Functions
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
DoStart ()
DoStop ()
Protected Attributes
IHandler Handler
Handler for incoming requests.
Detailed Description
HTTP connector.
Instances of this class wrap a TdjHTTPServer component.
Constructor & Destructor Documentation
TdjHTTPConnector()
TdjHTTPConnector::TdjHTTPConnector (const IHandler Handler)
Create a HTTP connector.
The handler is a required argument. The connector will call the "Handle" method for incoming requests.
Parameters
Handler the request handler
References TdjHTTPConnector(), Create(), and TdjAbstractConnector::Handler.
Referenced by TdjHTTPConnector().
~TdjHTTPConnector()
TdjHTTPConnector::~TdjHTTPConnector ()
Destructor.
References HTTPServer, TdjLifeCycle::IsStarted(), and TdjLifeCycle::Stop().
Member Function Documentation
CheckStarted()
TdjLifeCycle::CheckStarted () protected inherited
Raises an exception if the lifecycle is in "started" state.
References Started.
Referenced by TdjHTTPConnector::DoStart(), and TdjServer::DoStart().
CheckStopped()
TdjLifeCycle::CheckStopped () protected inherited
Raises an exception if the lifecycle is in "stopped" state.
References Stopped.
Referenced by TdjServer::DoStop().
DoStart()
TdjHTTPConnector::DoStart () protected
References TdjLifeCycle::CheckStarted(), TdjAbstractConnector::Host, HTTPServer, TdjAbstractConnector::Port, and TdjLifeCycle::Started.
DoStop()
TdjHTTPConnector::DoStop () protected
References HTTPServer, and TdjLifeCycle::IsStarted().
IsStarted()
Boolean TdjLifeCycle::IsStarted () inherited
Returns
True if component is started
Implements ILifeCycle.
Referenced by TdjHTTPConnector::~TdjHTTPConnector(), TdjHTTPConnector::DoStop(), TdjHandlerCollection::Handle(), and Start().
IsStopped()
Boolean TdjLifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implements ILifeCycle.
Start()
TdjLifeCycle::Start () inherited
Starts the component.
Implements ILifeCycle.
References DoStart(), IsStarted(), and Started.
Stop()
TdjLifeCycle::Stop () inherited
Stops the component.
Implements ILifeCycle.
References DoStop(), and Stopped.
Referenced by TdjHTTPConnector::~TdjHTTPConnector().
Member Data Documentation
Handler
IHandler TdjAbstractConnector::Handler protected inherited
Handler for incoming requests.
Referenced by TdjAbstractConnector(), TdjHTTPConnector::TdjHTTPConnector(), and DoStop().
Host
string TdjAbstractConnector::Host inherited
The host address for the connector.
See also
GetHost For reading
SetHost For writing
Referenced by TdjServer::AddConnector(), and TdjHTTPConnector::DoStart().
HTTPServer
TdjHTTPServer TdjHTTPConnector::HTTPServer
See also
FHTTPServer For reading
Referenced by ~TdjHTTPConnector(), DoStart(), and DoStop().
Port
Integer TdjAbstractConnector::Port inherited
The port number for the connector.
See also
GetPort For reading
SetPort For writing
Referenced by TdjHTTPConnector::DoStart().
Started
Boolean TdjLifeCycle::Started inherited
See also
FStarted For reading
SetStarted For writing
Referenced by TdjHandlerCollection::AddHandler(), CheckStarted(), TdjHTTPConnector::DoStart(), and Start().
Stopped
Boolean TdjLifeCycle::Stopped inherited
See also
FStopped For reading
SetStopped For writing
Referenced by CheckStopped(), and Stop().