Daraja HTTP Framework: TdjHandlerList Class Reference
TdjHandlerList Class Reference
Iterates handler list and exits when the response code is set.
Public Member Functions
TdjHandlerList ()
Constructor.
Boolean IsStarted ()
Boolean IsStopped ()
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
Boolean Started
Boolean Stopped
Protected Member Functions
AddHandler (const IHandler Handler)
Adds a handler to this container.
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
Handle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response)
Handles an HTTP request.
RemoveHandler (const IHandler Handler)
Removes a handler from this container.
Protected Attributes
TdjHandlers FHandlers
The handler collection.
Detailed Description
Iterates handler list and exits when the response code is set.
If the response code is still -1, it returns 404
This extension of TdjHandlerCollection will call each contained handler in turn until either an exception is thrown or a positive response status is set.
Constructor & Destructor Documentation
TdjHandlerList()
TdjHandlerList::TdjHandlerList ()
Constructor.
Referenced by Handle().
Member Function Documentation
AddHandler()
TdjHandlerCollection::AddHandler (const IHandler Handler) protected inherited
Adds a handler to this container.
Parameters
Handler Handler to add
Implements IHandlerContainer.
References Create().
CheckStarted()
TdjLifeCycle::CheckStarted () protected inherited
Raises an exception if the lifecycle is in "started" state.
References TdjLifeCycle().
CheckStopped()
TdjLifeCycle::CheckStopped () protected inherited
Raises an exception if the lifecycle is in "stopped" state.
References TdjLifeCycle(), and Started.
Handle()
TdjHandlerList::Handle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response) protected
Handles an HTTP request.
Parameters
Target Target path or resource identifier
Context Server context for this request
Request HTTP request object
Response HTTP response object to populate
Exceptions
EWebComponentException if an exception occurs that interferes with the component's normal operation.
Implements IHandler.
References TdjHandlerList().
IsStarted()
Boolean TdjLifeCycle::IsStarted () inherited
Returns
True if component is started
Implements ILifeCycle.
References Create().
Referenced by DoStart(), and TdjWebComponentHandler::FindHolder().
IsStopped()
Boolean TdjLifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implements ILifeCycle.
Referenced by DoStart().
RemoveHandler()
TdjHandlerCollection::RemoveHandler (const IHandler Handler) protected inherited
Removes a handler from this container.
Parameters
Handler Handler to remove
Implements IHandlerContainer.
Start()
TdjLifeCycle::Start () inherited
Starts the component.
Implements ILifeCycle.
References Stopped.
Stop()
TdjLifeCycle::Stop () inherited
Stops the component.
Implements ILifeCycle.
References TdjLifeCycle().
Referenced by DoStart(), and TdjWebComponentHandler::InvokeService().
Member Data Documentation
FHandlers
TdjHandlers TdjHandlerCollection::FHandlers protected inherited
The handler collection.
Referenced by TdjHandlerCollection(), and ~TdjHandlerCollection().
Started
Boolean TdjLifeCycle::Started inherited
Referenced by TdjHandlerCollection::~TdjHandlerCollection(), CheckStopped(), DoStop(), and TdjWebComponentHandler::InvokeService().
Stopped
Boolean TdjLifeCycle::Stopped inherited
Referenced by DoStop(), and Start().