Daraja HTTP Framework: TdjWebAppContext Class Reference
TdjWebAppContext Class Reference
Main context handler class.
Public Member Functions
TdjWebComponentHolder Add (TdjWebComponentClass ComponentClass, const string UrlPattern)
Add a Web Component.
TdjWebFilterHolder Add (TdjWebFilterClass FilterClass, const string UrlPattern)
Add a Web Filter, specifying a WebFilter class.
AddHandler (const IHandler Handler)
Add a handler to the container.
TdjWebComponentHolder AddWebComponent (TdjWebComponentClass ComponentClass, const string UrlPattern)
Add a Web Component.
TdjWebFilterHolder AddWebFilter (TdjWebFilterClass FilterClass, const string UrlPattern)
Add a Web Filter, specifying a WebFilter class.
IContext GetCurrentContext ()
The internal IContext field.
Boolean IsStarted ()
Boolean IsStopped ()
RemoveHandler (const IHandler Handler)
Removes a handler from this container.
SetInitParameter (const string Key, const string Value)
Set initialization parameter.
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
TStrings ConnectorNames
string ContextPath
IHandler ErrorHandler
IHandler Handler
Boolean Started
Boolean Stopped
Protected Member Functions
AddWebComponent (TdjWebComponentHolder Holder, const string UrlPattern)
Add a Web Component.
AddWebFilter (TdjWebFilterHolder Holder, const string UrlPattern)
Add a Web Filter Holder.
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
Boolean ContextMatches (const string ConnectorName, const string Target)
Check if the Document matches this context.
DoHandle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response)
DoStart ()
Start the handler.
DoStop ()
Start the handler.
TIdHTTPSession GetSession (TdjServerContext Context, TdjRequest Request, TdjResponse Response, const Boolean Create)
Get a HTTP session.
Handle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response)
Handles an HTTP request.
string ToConnectorName (TdjServerContext Context)
Creates connector name in the form 'host:port'.
Detailed Description
Main context handler class.
Member Function Documentation
Add() [1/2]
TdjWebComponentHolder TdjWebComponentContextHandler::Add (TdjWebComponentClass ComponentClass, const string UrlPattern) inherited
Add a Web Component.
Parameters
ComponentClass WebComponent class
UrlPattern path specification
Returns
the Web Component holder, which can be used for further configuration.
Exceptions
EWebComponentException if the Web Component can not be added
References DoHandle().
Add() [2/2]
TdjWebFilterHolder TdjWebComponentContextHandler::Add (TdjWebFilterClass FilterClass, const string UrlPattern) inherited
Add a Web Filter, specifying a WebFilter class.
Parameters
FilterClass WebFilter class
UrlPattern path specification
Returns
the Web Filter holder, which can be used for further configuration.
Exceptions
Exception if the WebFilter can not be added
AddHandler()
TdjHandlerWrapper::AddHandler (const IHandler Handler) inherited
Add a handler to the container.
This implementation of AddHandler calls SetHandler with the passed handler. If this HandlerWrapper had a previous wrapped handler, then it is passed to a call to AddHandler on the passed handler.
Parameters
Handler the handler to be added
Implements IHandlerContainer.
AddWebComponent() [1/2]
TdjWebComponentHolder TdjWebComponentContextHandler::AddWebComponent (TdjWebComponentClass ComponentClass, const string UrlPattern) inherited
Add a Web Component.
Parameters
ComponentClass WebComponent class
UrlPattern path specification
Returns
the Web Component holder, which can be used for further configuration.
Exceptions
EWebComponentException if the Web Component can not be added
References TdjWebComponentContextHandler(), AddWebFilter(), TdjContextHandler::ContextMatches(), TdjContextHandler::ContextPath, TdjHandlerWrapper::GetSession(), Handle(), and TdjContextHandler::ToConnectorName().
AddWebComponent() [2/2]
TdjWebComponentContextHandler::AddWebComponent (TdjWebComponentHolder Holder, const string UrlPattern) protected inherited
Add a Web Component.
Parameters
Holder holds information about the Web Component
UrlPattern path specification
Exceptions
EWebComponentException if the Web Component can not be added
Deprecated
for removal
Referenced by TdjWebComponentContextHandler().
AddWebFilter() [1/2]
TdjWebFilterHolder TdjWebComponentContextHandler::AddWebFilter (TdjWebFilterClass FilterClass, const string UrlPattern) inherited
Add a Web Filter, specifying a WebFilter class.
Parameters
FilterClass WebFilter class
UrlPattern path specification
Returns
the Web Filter holder, which can be used for further configuration.
Exceptions
Exception if the WebFilter can not be added
AddWebFilter() [2/2]
TdjWebComponentContextHandler::AddWebFilter (TdjWebFilterHolder Holder, const string UrlPattern) protected inherited
Add a Web Filter Holder.
Parameters
Holder holds information about the Web Filter
UrlPattern path specification
Exceptions
Exception if the Web Filter can not be added
Deprecated
for removal
Referenced by AddWebComponent().
CheckStarted()
TdjLifeCycle::CheckStarted () protected inherited
Raises an exception if the lifecycle is in "started" state.
References TdjLifeCycle().
CheckStopped()
TdjLifeCycle::CheckStopped () protected inherited
Raises an exception if the lifecycle is in "stopped" state.
References TdjLifeCycle(), and Started.
ContextMatches()
Boolean TdjContextHandler::ContextMatches (const string ConnectorName, const string Target) protected inherited
Check if the Document matches this context.
Parameters
ConnectorName the connector name (like 'host:port'
Target the target URL document
Returns
True if the context matches the connector name and target URL document
Referenced by TdjWebComponentContextHandler::AddWebComponent().
DoHandle()
TdjWebComponentContextHandler::DoHandle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response) protected inherited
Parameters
Target Request target
Context HTTP server context
Request HTTP request
Response HTTP response
Referenced by Add().
DoStart()
TdjContextHandler::DoStart () protected inherited
Start the handler.
See also
TdjLifeCycle
DoStop()
TdjContextHandler::DoStop () protected inherited
Start the handler.
See also
TdjLifeCycle
GetCurrentContext()
IContext TdjContextHandler::GetCurrentContext () inherited
The internal IContext field.
Referenced by TdjWebComponentContextHandler::TdjWebComponentContextHandler().
GetSession()
TIdHTTPSession TdjHandlerWrapper::GetSession (TdjServerContext Context, TdjRequest Request, TdjResponse Response, const Boolean Create) protected inherited
Get a HTTP session.
References TdjHandlerWrapper(), Create(), and Handler.
Referenced by TdjWebComponentContextHandler::AddWebComponent().
Handle()
TdjWebComponentContextHandler::Handle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response) protected inherited
Handles an HTTP request.
Parameters
Target Target path or resource identifier
Context Server context for this request
Request HTTP request object
Response HTTP response object to populate
Exceptions
EWebComponentException if an exception occurs that interferes with the component's normal operation.
Implements IHandler.
Referenced by AddWebComponent().
IsStarted()
Boolean TdjLifeCycle::IsStarted () inherited
Returns
True if component is started
Implements ILifeCycle.
References Create().
Referenced by DoStart(), and TdjWebComponentHandler::FindHolder().
IsStopped()
Boolean TdjLifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implements ILifeCycle.
Referenced by DoStart().
RemoveHandler()
TdjHandlerWrapper::RemoveHandler (const IHandler Handler) inherited
Removes a handler from this container.
Parameters
Handler Handler to remove
Implements IHandlerContainer.
References Handler.
SetInitParameter()
TdjContextHandler::SetInitParameter (const string Key, const string Value) inherited
Set initialization parameter.
Parameters
Key init parameter name
Value init parameter value
Start()
TdjLifeCycle::Start () inherited
Starts the component.
Implements ILifeCycle.
References Stopped.
Stop()
TdjLifeCycle::Stop () inherited
Stops the component.
Implements ILifeCycle.
References TdjLifeCycle().
Referenced by DoStart(), and TdjWebComponentHandler::InvokeService().
ToConnectorName()
string TdjContextHandler::ToConnectorName (TdjServerContext Context) protected inherited
Creates connector name in the form 'host:port'.
Returns
connector name
Referenced by TdjWebComponentContextHandler::AddWebComponent().
Member Data Documentation
ConnectorNames
TStrings TdjContextHandler::ConnectorNames inherited
ContextPath
string TdjContextHandler::ContextPath inherited
Referenced by TdjWebComponentContextHandler::AddWebComponent().
ErrorHandler
IHandler TdjContextHandler::ErrorHandler inherited
Handler
IHandler TdjHandlerWrapper::Handler inherited
Referenced by GetSession(), and RemoveHandler().
Started
Boolean TdjLifeCycle::Started inherited
Referenced by TdjHandlerCollection::~TdjHandlerCollection(), CheckStopped(), DoStop(), and TdjWebComponentHandler::InvokeService().
Stopped
Boolean TdjLifeCycle::Stopped inherited
Referenced by DoStop(), and Start().