Daraja HTTP Framework: IConnector Interface Reference
IConnector Interface Reference
Interface for HTTP connectors.
Public Member Functions
string GetHost ()
Get the host.
Integer GetPort ()
Get the port.
boolean IsStarted ()
boolean IsStopped ()
SetHost (const string Value)
Set the host.
SetPort (Integer Value)
Set the port.
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
string Host
Integer Port
Detailed Description
Interface for HTTP connectors.
Member Function Documentation
GetHost()
string IConnector::GetHost ()
Get the host.
GetPort()
Integer IConnector::GetPort ()
Get the port.
IsStarted()
boolean ILifeCycle::IsStarted () inherited
Returns
True if component is started
Implemented in TdjLifeCycle.
Referenced by TdjServer::~TdjServer(), TdjServer::AddConnector(), and TdjHandlerCollection::RemoveHandler().
IsStopped()
boolean ILifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implemented in TdjLifeCycle.
SetHost()
IConnector::SetHost (const string Value)
Set the host.
SetPort()
IConnector::SetPort (Integer Value)
Set the port.
Start()
ILifeCycle::Start () inherited
Starts the component.
Implemented in TdjLifeCycle.
Referenced by TdjServer::AddConnector(), and TdjHandlerCollection::AddHandler().
Stop()
ILifeCycle::Stop () inherited
Stops the component.
Implemented in TdjLifeCycle.
Referenced by TdjServer::~TdjServer(), and TdjHandlerCollection::RemoveHandler().
Member Data Documentation
Host
string IConnector::Host
See also
GetHost For reading
SetHost For writing
Referenced by TdjServer::AddConnector().
Port
Integer IConnector::Port
See also
GetPort For reading
SetPort For writing
Referenced by TdjServer::AddConnector().