Daraja HTTP Framework: TdjServerBase Class Reference
TdjServerBase Class Reference
Base server implementation providing core HTTP server functionality.
Public Member Functions
TdjServerBase ()
Create a ServerBase instance.
~TdjServerBase ()
Destructor.
AddHandler (const IHandler Handler)
Add a handler to the container.
Boolean IsStarted ()
Boolean IsStopped ()
RemoveHandler (const IHandler Handler)
Removes a handler from this container.
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
IHandler Handler
Boolean Started
Boolean Stopped
Protected Member Functions
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
DoStart ()
Start the server.
DoStop ()
Stop the server.
TIdHTTPSession GetSession (TdjServerContext Context, TdjRequest Request, TdjResponse Response, const Boolean Create)
Get a HTTP session.
Handle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response)
Handles an HTTP request.
Detailed Description
Base server implementation providing core HTTP server functionality.
This class serves as a foundation for HTTP servers in the Daraja framework, implementing both IHandlerContainer and basic request handling capabilities.
See also
IHandlerContainer
TdjHandlerWrapper
Constructor & Destructor Documentation
TdjServerBase()
TdjServerBase::TdjServerBase ()
Create a ServerBase instance.
References TdjServerBase(), and Create().
Referenced by TdjServerBase().
~TdjServerBase()
TdjServerBase::~TdjServerBase ()
Destructor.
Member Function Documentation
AddHandler()
TdjHandlerWrapper::AddHandler (const IHandler Handler) inherited
Add a handler to the container.
This implementation of AddHandler calls SetHandler with the passed handler. If this HandlerWrapper had a previous wrapped handler, then it is passed to a call to AddHandler on the passed handler.
Parameters
Handler the handler to be added
Implements IHandlerContainer.
References Handler.
Referenced by TdjServer::TdjServer(), and TdjWebComponentContextHandler::TdjWebComponentContextHandler().
CheckStarted()
TdjLifeCycle::CheckStarted () protected inherited
Raises an exception if the lifecycle is in "started" state.
References Started.
Referenced by TdjHTTPConnector::DoStart(), and TdjServer::DoStart().
CheckStopped()
TdjLifeCycle::CheckStopped () protected inherited
Raises an exception if the lifecycle is in "stopped" state.
References Stopped.
Referenced by TdjServer::DoStop().
DoStart()
TdjServerBase::DoStart () protected
Start the server.
Note
This method calls the inherited implementation and logs the server start.
Exceptions
EWebComponentException if the server fails to start
DoStop()
TdjServerBase::DoStop () protected
Stop the server.
Note
This method calls the inherited implementation and logs the server stop.
Exceptions
EWebComponentException if the server fails to stop cleanly
GetSession()
TIdHTTPSession TdjHandlerWrapper::GetSession (TdjServerContext Context, TdjRequest Request, TdjResponse Response, const Boolean Create) protected inherited
Get a HTTP session.
References Create().
Referenced by TdjWebComponentContextHandler::Handle().
Handle()
TdjServerBase::Handle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response) protected
Handles an HTTP request.
Parameters
Target Target path or resource identifier
Context Server context for this request
Request HTTP request object
Response HTTP response object to populate
Exceptions
EWebComponentException if an exception occurs that interferes with the component's normal operation.
Implements IHandler.
IsStarted()
Boolean TdjLifeCycle::IsStarted () inherited
Returns
True if component is started
Implements ILifeCycle.
Referenced by TdjHTTPConnector::~TdjHTTPConnector(), TdjHTTPConnector::DoStop(), TdjHandlerCollection::Handle(), and Start().
IsStopped()
Boolean TdjLifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implements ILifeCycle.
RemoveHandler()
TdjHandlerWrapper::RemoveHandler (const IHandler Handler) inherited
Removes a handler from this container.
Parameters
Handler Handler to remove
Implements IHandlerContainer.
References Handler.
Start()
TdjLifeCycle::Start () inherited
Starts the component.
Implements ILifeCycle.
References DoStart(), IsStarted(), and Started.
Stop()
TdjLifeCycle::Stop () inherited
Stops the component.
Implements ILifeCycle.
References DoStop(), and Stopped.
Referenced by TdjHTTPConnector::~TdjHTTPConnector().
Member Data Documentation
Handler
IHandler TdjHandlerWrapper::Handler inherited
See also
GetHandler For reading
SetHandler For writing
Referenced by AddHandler(), DoStop(), Handle(), and RemoveHandler().
Started
Boolean TdjLifeCycle::Started inherited
See also
FStarted For reading
SetStarted For writing
Referenced by TdjHandlerCollection::AddHandler(), CheckStarted(), TdjHTTPConnector::DoStart(), and Start().
Stopped
Boolean TdjLifeCycle::Stopped inherited
See also
FStopped For reading
SetStopped For writing
Referenced by CheckStopped(), and Stop().