Daraja HTTP Framework: TdjAbstractHandler Class Reference
TdjAbstractHandler Class Reference
AbstractHandler.
Public Member Functions
TdjAbstractHandler ()
Constructor.
Boolean IsStarted ()
Boolean IsStopped ()
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
Boolean Started
Boolean Stopped
Protected Member Functions
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
DoStart ()
DoStop ()
Handle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response)
Handles an HTTP request.
Detailed Description
AbstractHandler.
Constructor & Destructor Documentation
TdjAbstractHandler()
TdjAbstractHandler::TdjAbstractHandler ()
Constructor.
References TdjAbstractHandler(), and Create().
Referenced by TdjAbstractHandler().
Member Function Documentation
CheckStarted()
TdjLifeCycle::CheckStarted () protected inherited
Raises an exception if the lifecycle is in "started" state.
References Started.
Referenced by TdjHTTPConnector::DoStart(), and TdjServer::DoStart().
CheckStopped()
TdjLifeCycle::CheckStopped () protected inherited
Raises an exception if the lifecycle is in "stopped" state.
References Stopped.
Referenced by TdjServer::DoStop().
DoStart()
TdjAbstractHandler::DoStart () protected
DoStop()
TdjAbstractHandler::DoStop () protected
Handle()
TdjAbstractHandler::Handle (const string Target, TdjServerContext Context, TdjRequest Request, TdjResponse Response) protected
Handles an HTTP request.
Parameters
Target Target path or resource identifier
Context Server context for this request
Request HTTP request object
Response HTTP response object to populate
Exceptions
EWebComponentException if an exception occurs that interferes with the component's normal operation.
Implements IHandler.
IsStarted()
Boolean TdjLifeCycle::IsStarted () inherited
Returns
True if component is started
Implements ILifeCycle.
Referenced by TdjHTTPConnector::~TdjHTTPConnector(), TdjHTTPConnector::DoStop(), TdjHandlerCollection::Handle(), and Start().
IsStopped()
Boolean TdjLifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implements ILifeCycle.
Start()
TdjLifeCycle::Start () inherited
Starts the component.
Implements ILifeCycle.
References DoStart(), IsStarted(), and Started.
Stop()
TdjLifeCycle::Stop () inherited
Stops the component.
Implements ILifeCycle.
References DoStop(), and Stopped.
Referenced by TdjHTTPConnector::~TdjHTTPConnector().
Member Data Documentation
Started
Boolean TdjLifeCycle::Started inherited
See also
FStarted For reading
SetStarted For writing
Referenced by TdjHandlerCollection::AddHandler(), CheckStarted(), TdjHTTPConnector::DoStart(), and Start().
Stopped
Boolean TdjLifeCycle::Stopped inherited
See also
FStopped For reading
SetStopped For writing
Referenced by CheckStopped(), and Stop().