Daraja HTTP Framework: TdjAbstractConnector Class Reference
TdjAbstractConnector Class Reference
Interface for HTTP connectors.
Public Member Functions
TdjAbstractConnector (const IHandler Handler)
Constructor.
~TdjAbstractConnector ()
Destructor.
Boolean IsStarted ()
Boolean IsStopped ()
Start ()
Starts the component.
Stop ()
Stops the component.
Public Attributes
string Host
The host address for the connector.
Integer Port
The port number for the connector.
Boolean Started
Boolean Stopped
Protected Member Functions
CheckStarted ()
Raises an exception if the lifecycle is in "started" state.
CheckStopped ()
Raises an exception if the lifecycle is in "stopped" state.
DoStart ()
Start the connector.
DoStop ()
Stop the connector.
Protected Attributes
IHandler Handler
Handler for incoming requests.
Detailed Description
Interface for HTTP connectors.
Abstract connector class for handling incoming requests. This class provides the basic structure for connectors, including properties for host and port, and methods for starting and stopping the connector.
Constructor & Destructor Documentation
TdjAbstractConnector()
TdjAbstractConnector::TdjAbstractConnector (const IHandler Handler)
Constructor.
Initializes the connector with the specified request handler.
Parameters
Handler The request handler. The connector will call the "Handle" method for incoming requests.
Exceptions
AssertionError if the handler is not assigned.
References TdjAbstractConnector(), Create(), and Handler.
Referenced by TdjAbstractConnector(), ~TdjAbstractConnector(), and DoStop().
~TdjAbstractConnector()
TdjAbstractConnector::~TdjAbstractConnector ()
Destructor.
Cleans up resources and ensures the connector is stopped before destruction.
References TdjAbstractConnector().
Member Function Documentation
CheckStarted()
TdjLifeCycle::CheckStarted () protected inherited
Raises an exception if the lifecycle is in "started" state.
References TdjLifeCycle().
CheckStopped()
TdjLifeCycle::CheckStopped () protected inherited
Raises an exception if the lifecycle is in "stopped" state.
References TdjLifeCycle(), and Started.
DoStart()
TdjAbstractConnector::DoStart () protected
Start the connector.
This method is called to initialize and start the connector's operations.
DoStop()
TdjAbstractConnector::DoStop () protected
Stop the connector.
This method is called to terminate the connector's operations.
References TdjAbstractConnector().
IsStarted()
Boolean TdjLifeCycle::IsStarted () inherited
Returns
True if component is started
Implements ILifeCycle.
References Create().
Referenced by DoStart(), and TdjWebComponentHandler::FindHolder().
IsStopped()
Boolean TdjLifeCycle::IsStopped () inherited
Returns
True if component is stopped
Implements ILifeCycle.
Referenced by DoStart().
Start()
TdjLifeCycle::Start () inherited
Starts the component.
Implements ILifeCycle.
References Stopped.
Stop()
TdjLifeCycle::Stop () inherited
Stops the component.
Implements ILifeCycle.
References TdjLifeCycle().
Referenced by DoStart(), and TdjWebComponentHandler::InvokeService().
Member Data Documentation
Handler
IHandler TdjAbstractConnector::Handler protected
Handler for incoming requests.
Referenced by TdjAbstractConnector().
Host
string TdjAbstractConnector::Host
The host address for the connector.
Port
Integer TdjAbstractConnector::Port
The port number for the connector.
Started
Boolean TdjLifeCycle::Started inherited
Referenced by TdjHandlerCollection::~TdjHandlerCollection(), CheckStopped(), DoStop(), and TdjWebComponentHandler::InvokeService().
Stopped
Boolean TdjLifeCycle::Stopped inherited
Referenced by DoStop(), and Start().