Daraja HTTP Framework: ILifeCycle Interface Reference
ILifeCycle Interface Reference
Interface for components with a lifecycle (start/stop capabilities).
Public Member Functions
boolean IsStarted ()
boolean IsStopped ()
Start ()
Starts the component.
Stop ()
Stops the component.
Detailed Description
Interface for components with a lifecycle (start/stop capabilities).
Member Function Documentation
IsStarted()
boolean ILifeCycle::IsStarted ()
Returns
True if component is started
Implemented in TdjLifeCycle.
Referenced by TdjServer::~TdjServer(), TdjServer::AddConnector(), and TdjHandlerCollection::RemoveHandler().
IsStopped()
boolean ILifeCycle::IsStopped ()
Returns
True if component is stopped
Implemented in TdjLifeCycle.
Start()
ILifeCycle::Start ()
Starts the component.
Implemented in TdjLifeCycle.
Referenced by TdjServer::AddConnector(), and TdjHandlerCollection::AddHandler().
Stop()
ILifeCycle::Stop ()
Stops the component.
Implemented in TdjLifeCycle.
Referenced by TdjServer::~TdjServer(), and TdjHandlerCollection::RemoveHandler().