Daraja HTTP Framework: djGenericHolder.pas File Reference
djGenericHolder.pas File Reference
Classes
class TdjGenericHolder
A generic holder class that manages objects of type T.
Functions
<> Create (TInterfacedClass AClass)
Function Documentation
Create()
<> Create (TInterfacedClass AClass)
References Create().
Referenced by TdjAbstractConnector::TdjAbstractConnector(), TdjAbstractHandler::TdjAbstractHandler(), TdjContextHandlerCollection::TdjContextHandlerCollection(), TdjGenericWebComponent::TdjGenericWebComponent(), TdjHandlerCollection::TdjHandlerCollection(), TdjHandlerList::TdjHandlerList(), TdjHandlerWrapper::TdjHandlerWrapper(), TdjHTTPConnector::TdjHTTPConnector(), TdjHTTPServer::TdjHTTPServer(), TdjLifeCycle::TdjLifeCycle(), TdjServer::TdjServer(), TdjServer::TdjServer(), TdjServer::TdjServer(), TdjServerBase::TdjServerBase(), TdjWebComponentContextHandler::TdjWebComponentContextHandler(), TdjWebComponentHolder::TdjWebComponentHolder(), TdjWebFilterChain::TdjWebFilterChain(), TdjWebFilterHolder::TdjWebFilterHolder(), Create(), TdjGenericWebComponent::GetSession(), and TdjHandlerWrapper::GetSession().