Daraja HTTP Framework: djMultiMap.pas File Reference
djMultiMap.pas File Reference
Classes
class TdjMultiMap
A generic multi-map implementation that maps strings to lists of objects.
Functions
<> Add (const string Key, T Value)
<> Destroy ()
<><> TObjectList T (const string Key)
Function Documentation
Add()
<> Add (const string Key, T Value)
Destroy()
<> Destroy ()
References T().
Referenced by TdjLifeCycle::DoStart().
T()
<><> TObjectList T (const string Key)
Referenced by Destroy().